name: amin_agent
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_svg: ^2.0.3
  confetti: ^0.7.0
  cached_network_image: ^3.2.1
  connectivity_plus: ^5.0.2
  http: ^1.1.2
  material_dialogs: ^1.1.4
  pin_code_fields: ^8.0.1
  device_preview: ^1.1.0
  readmore: ^2.2.0
  responsive_sizer: ^3.2.0
  circular_profile_avatar: ^2.0.5
  fl_chart: ^0.66.0
  badges: ^3.1.2
  get_storage: ^2.0.6
  bottom_bar_matu: ^1.3.1
  panara_dialogs: ^0.1.4
  calendar_date_picker2: ^0.5.3
  intl: ^0.18.1
  image_picker: ^1.0.7
  file_picker: ^6.1.1
  flutter_spinkit: ^5.2.0
  image: ^4.1.4
  easy_pdf_viewer: ^1.0.7
  shimmer: ^3.0.0
  geocoding: ^2.0.0
  google_maps_flutter: ^2.4.0
  location: ^5.0.3

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/gif/

fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/rubik/Rubik-Regular.ttf
        - asset: assets/fonts/rubik/Rubik-Black.ttf
        - asset: assets/fonts/rubik/Rubik-BlackItalic.ttf
        - asset: assets/fonts/rubik/Rubik-Bold.ttf
        - asset: assets/fonts/rubik/Rubik-BoldItalic.ttf
        - asset: assets/fonts/rubik/Rubik-ExtraBold.ttf
        - asset: assets/fonts/rubik/Rubik-ExtraBoldItalic.ttf
        - asset: assets/fonts/rubik/Rubik-Light.ttf
        - asset: assets/fonts/rubik/Rubik-Medium.ttf
        - asset: assets/fonts/rubik/Rubik-SemiBoldItalic.ttf
        - asset: assets/fonts/rubik/Rubik-SemiBold.ttf
          style: Regular