name: amin_agent
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_svg: ^2.0.9
  adaptive_dialog: ^2.0.0
  confetti: ^0.7.0
  animated_notch_bottom_bar: ^1.0.0
  cached_network_image: ^3.2.1
  connectivity_plus: ^4.0.2
  google_maps_flutter: ^2.4.0
  location: ^5.0.3
  http: ^1.1.2
  material_dialogs: ^1.1.4
  sms_otp_auto_verify: ^2.1.0
  otp_text_field: ^1.1.3
  device_preview: ^1.1.0
  readmore: ^2.2.0
  responsive_sizer: ^3.2.0
  circular_profile_avatar: ^2.0.5
  fl_chart: ^0.66.0


dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/

fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/rubik/Rubik-Regular.ttf
        - asset: assets/fonts/rubik/Rubik-Black.ttf
        - asset: assets/fonts/rubik/Rubik-BlackItalic.ttf
        - asset: assets/fonts/rubik/Rubik-Bold.ttf
        - asset: assets/fonts/rubik/Rubik-BoldItalic.ttf
        - asset: assets/fonts/rubik/Rubik-ExtraBold.ttf
        - asset: assets/fonts/rubik/Rubik-ExtraBoldItalic.ttf
        - asset: assets/fonts/rubik/Rubik-Light.ttf
        - asset: assets/fonts/rubik/Rubik-Medium.ttf
        - asset: assets/fonts/rubik/Rubik-SemiBoldItalic.ttf
        - asset: assets/fonts/rubik/Rubik-SemiBold.ttf
          style: Regular