// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpQdAHC0l8pMGMIvUiQHid9IVbMz3xbzk',
    appId: '1:829287823878:web:6eb676afeef47744dca187',
    messagingSenderId: '829287823878',
    projectId: 'mpo-flutter-514b5',
    authDomain: 'mpo-flutter-514b5.firebaseapp.com',
    storageBucket: 'mpo-flutter-514b5.appspot.com',
    measurementId: 'G-P7PFPYDBR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt7_bddufmXCTch1u_6OZjfXAxFJUQyII',
    appId: '1:829287823878:android:9fd78db097185d49dca187',
    messagingSenderId: '829287823878',
    projectId: 'mpo-flutter-514b5',
    storageBucket: 'mpo-flutter-514b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6Fc8V8E77T5AliLFoAI-12ISV78F0LJk',
    appId: '1:829287823878:ios:b28d52c23c9856d2dca187',
    messagingSenderId: '829287823878',
    projectId: 'mpo-flutter-514b5',
    storageBucket: 'mpo-flutter-514b5.appspot.com',
    iosBundleId: 'com.example.aminAgent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6Fc8V8E77T5AliLFoAI-12ISV78F0LJk',
    appId: '1:829287823878:ios:c1982df050f507c8dca187',
    messagingSenderId: '829287823878',
    projectId: 'mpo-flutter-514b5',
    storageBucket: 'mpo-flutter-514b5.appspot.com',
    iosBundleId: 'com.example.aminAgent.RunnerTests',
  );
}
